/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "tdata.h"

bool_t
xdr_taggeddata (XDR *xdrs, taggeddata *objp)
{
	register int32_t *buf;

	 if (!xdr_char (xdrs, &objp->done))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->value))
		 return FALSE;
	return TRUE;
}
